@extends('adminlte::page')
@section('content')
    <div id="index">
        <span>欢迎登录小米商城后台控制中心</span>
    </div>
@endsection
@section('css')
    <style>
        #index
        {
            width:100%;
            height:880px;
            font-size:65px;
            text-align:center;
            line-height:300px;
            color:orange;
            background-image:url('/images/mi.jpg');
            background-repeat:no-repeat;
            background-size:100%;
        }
    </style>
@endsection