@extends('adminlte::page')
@section('content')
    <div id="index">
        <h4>欢迎登录小米商城后台控制中心</h4>
    </div>
@endsection
@section('css')
    <style>
        #index
        {
            width:100%;
            height:880px;
            background-image:url('/images/mi.jpg');
            background-repeat:no-repeat;
            background-size:100%;
        }
        h4{
            position:abslute;
            font-size:2rem;
            line-height:80px;
            text-align:center;
            color:orange;
        }
    </style>
@endsection